
import Nav from "@/components/pages/Dashboard/nav";
import SideNav from "@/components/pages/Dashboard/sidenav";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div lang="en">
            <SideNav />
            {children}
        </div>
    );
}
